#:kivy 1.11.1

<GradientTab>:
    text: "palette"

    loop_gradient: loop_checkbox.active
    black_inside: black_inside_checkbox.active

    BoxLayout:
        MDLabel:
            text: "Loop gradient ?"
        MDCheckbox:
            id: loop_checkbox
            active: True

    BoxLayout:
        MDLabel:
            text: "Black inside ?"
        MDCheckbox:
            id: black_inside_checkbox
            value: True
